import asyncio
import random
import string
from telethon import events
from checker import is_valid_token

# Dictionary to store user IDs and their tokens
user_tokens = {}

@client.on(events.NewMessage(pattern="^/token$"))
async def generate_token(event):
    user_id = event.sender_id
    if user_id not in user_tokens:
        # Generate a new token for the user
        token = 'Adi_' + ''.join(random.choices(string.ascii_uppercase + string.digits, k=5)) + '_iux'
        user_tokens[user_id] = token
    else:
        # Retrieve user's existing token
        token = user_tokens[user_id]
    response = f"Your token: `{token}`\n\nBy -- Iconic Robot"
    await event.respond(response, parse_mode='markdown')

@client.on(events.NewMessage(pattern="^/ctoken (.*)"))
async def check_token(event):
    token_to_check = event.pattern_match.group(1)
    if is_valid_token(token_to_check):
        await event.respond("This token was generated by the bot.")
    else:
        await event.respond("This token was not generated by the bot.")

__mod_name__ = "Token System"
__help__ = """
/token: Generate a unique token for yourself.
/ctoken [token]: Check if the provided token was generated by the bot.
"""
